use myplatform;

INSERT INTO `Country` (`CountryID`,`Code`,`Name`,`LanguageKey`, `DisplayOrder`) VALUES 
 (1,'af','Afghanistan','country.af'),
 (2,'ax','Aland Islands','country.ax'),
 (3,'al','Albania','country.al'),
 (4,'dz','Algeria','country.dz'),
 (5,'as','American Samoa','country.as'),
 (6,'ad','Andorra','country.ad'),
 (7,'ao','Angola','country.ao'),
 (8,'ai','Anguilla','country.ai'),
 (9,'aq','Antarctica','country.aq'),
 (10,'ag','Antigua and Barbuda','country.ag'),
 (11,'ar','Argentina','country.ar'),
 (12,'am','Armenia','country.am'),
 (13,'aw','Aruba','country.aw'),
 (14,'au','Australia','country.au'),
 (15,'at','Austria','country.at'),
 (16,'az','Azerbaijan','country.az'),
 (17,'bs','Bahamas','country.bs'),
 (18,'bh','Bahrain','country.bh'),
 (19,'bd','Bangladesh','country.bd'),
 (20,'bb','Barbados','country.bb'),
 (21,'by','Belarus','country.by'),
 (22,'be','Belgium','country.be'),
 (23,'bz','Belize','country.bz'),
 (24,'bj','Benin','country.bj'),
 (25,'bm','Bermuda','country.bm'),
 (26,'bt','Bhutan','country.bt'),
 (27,'bo','Bolivia','country.bo'),
 (28,'ba','Bosnia and Herzegovina','country.ba'),
 (29,'bw','Botswana','country.bw'),
 (30,'bv','Bouvet Island','country.bv'),
 (31,'br','Brazil','country.br'),
 (32,'io','British Indian Ocean Territory','country.io'),
 (33,'vg','British Virgin Islands','country.vg'),
 (34,'bn','Brunei','country.bn'),
 (35,'bg','Bulgaria','country.bg'),
 (36,'bf','Burkina Faso','country.bf'),
 (37,'bi','Burundi','country.bi'),
 (38,'kh','Cambodia','country.kh'),
 (39,'cm','Cameroon','country.cm'),
 (40,'ca','Canada','country.ca'),
 (41,'cv','Cape Verde','country.cv'),
 (42,'ky','Cayman Islands','country.ky'),
 (43,'cf','Central African Republic','country.cf'),
 (44,'td','Chad','country.td'),
 (45,'cl','Chile','country.cl'),
 (46,'cn','China','country.cn'),
 (47,'cx','Christmas Island','country.cx'),
 (48,'cc','Cocos (Keeling) Islands','country.cc'),
 (49,'co','Colombia','country.co'),
 (50,'km','Comoros','country.km'),
 (51,'cg','Congo','country.cg'),
 (52,'ck','Cook Islands','country.ck'),
 (53,'cr','Costa Rica','country.cr'),
 (54,'hr','Croatia','country.hr'),
 (55,'cu','Cuba','country.cu'),
 (56,'cy','Cyprus','country.cy'),
 (57,'cz','Czech Republic','country.cz'),
 (58,'cd','Democratic Republic of Congo','country.cd'),
 (59,'dk','Denmark','country.dk'),
 (60,'xx','Disputed Territory','country.xx'),
 (61,'dj','Djibouti','country.dj'),
 (62,'dm','Dominica','country.dm'),
 (63,'do','Dominican Republic','country.do'),
 (64,'tl','East Timor','country.tl'),
 (65,'ec','Ecuador','country.ec'),
 (66,'eg','Egypt','country.eg'),
 (67,'sv','El Salvador','country.sv'),
 (68,'gq','Equatorial Guinea','country.gq'),
 (69,'er','Eritrea','country.er'),
 (70,'ee','Estonia','country.ee'),
 (71,'et','Ethiopia','country.et'),
 (72,'fk','Falkland Islands','country.fk'),
 (73,'fo','Faroe Islands','country.fo'),
 (74,'fm','Federated States of Micronesia','country.fm'),
 (75,'fj','Fiji','country.fj'),
 (76,'fi','Finland','country.fi'),
 (77,'fr','France','country.fr'),
 (78,'gf','French Guyana','country.gf'),
 (79,'pf','French Polynesia','country.pf'),
 (80,'tf','French Southern Territories','country.tf'),
 (81,'ga','Gabon','country.ga'),
 (82,'gm','Gambia','country.gm'),
 (83,'ge','Georgia','country.ge'),
 (84,'de','Germany','country.de'),
 (85,'gh','Ghana','country.gh'),
 (86,'gi','Gibraltar','country.gi'),
 (87,'gr','Greece','country.gr'),
 (88,'gl','Greenland','country.gl'),
 (89,'gd','Grenada','country.gd'),
 (90,'gp','Guadeloupe','country.gp'),
 (91,'gu','Guam','country.gu'),
 (92,'gt','Guatemala','country.gt'),
 (93,'gn','Guinea','country.gn'),
 (94,'gw','Guinea-Bissau','country.gw'),
 (95,'gy','Guyana','country.gy'),
 (96,'ht','Haiti','country.ht'),
 (97,'hm','Heard Island and Mcdonald Islands','country.hm'),
 (98,'hn','Honduras','country.hn'),
 (99,'hk','Hong Kong','country.hk'),
 (100,'hu','Hungary','country.hu'),
 (101,'is','Iceland','country.is'),
 (102,'in','India','country.in'),
 (103,'id','Indonesia','country.id'),
 (104,'ir','Iran','country.ir'),
 (105,'iq','Iraq','country.iq'),
 (106,'xe','Iraq-Saudi Arabia Neutral Zone','country.xe'),
 (107,'ie','Ireland','country.ie'),
 (108,'il','Israel','country.il'),
 (109,'it','Italy','country.it'),
 (110,'ci','Ivory Coast','country.ci'),
 (111,'jm','Jamaica','country.jm'),
 (112,'jp','Japan','country.jp'),
 (113,'jo','Jordan','country.jo'),
 (114,'kz','Kazakhstan','country.kz'),
 (115,'ke','Kenya','country.ke'),
 (116,'ki','Kiribati','country.ki'),
 (117,'kw','Kuwait','country.kw'),
 (118,'kg','Kyrgyzstan','country.kg'),
 (119,'la','Laos','country.la'),
 (120,'lv','Latvia','country.lv'),
 (121,'lb','Lebanon','country.lb'),
 (122,'ls','Lesotho','country.ls'),
 (123,'lr','Liberia','country.lr'),
 (124,'ly','Libya','country.ly'),
 (125,'li','Liechtenstein','country.li'),
 (126,'lt','Lithuania','country.lt'),
 (127,'lu','Luxembourg','country.lu'),
 (128,'mo','Macau','country.mo'),
 (129,'mk','Macedonia','country.mk'),
 (130,'mg','Madagascar','country.mg'),
 (131,'mw','Malawi','country.mw'),
 (132,'my','Malaysia','country.my'),
 (133,'mv','Maldives','country.mv'),
 (134,'ml','Mali','country.ml'),
 (135,'mt','Malta','country.mt'),
 (136,'mh','Marshall Islands','country.mh'),
 (137,'mq','Martinique','country.mq'),
 (138,'mr','Mauritania','country.mr'),
 (139,'mu','Mauritius','country.mu'),
 (140,'yt','Mayotte','country.yt'),
 (141,'mx','Mexico','country.mx'),
 (142,'md','Moldova','country.md'),
 (143,'mc','Monaco','country.mc'),
 (144,'mn','Mongolia','country.mn'),
 (145,'ms','Montserrat','country.ms'),
 (146,'ma','Morocco','country.ma'),
 (147,'mz','Mozambique','country.mz'),
 (148,'mm','Myanmar','country.mm'),
 (149,'na','Namibia','country.na'),
 (150,'nr','Nauru','country.nr'),
 (151,'np','Nepal','country.np'),
 (152,'nl','Netherlands','country.nl'),
 (153,'an','Netherlands Antilles','country.an'),
 (154,'nc','New Caledonia','country.nc'),
 (155,'nz','New Zealand','country.nz'),
 (156,'ni','Nicaragua','country.ni'),
 (157,'ne','Niger','country.ne'),
 (158,'ng','Nigeria','country.ng'),
 (159,'nu','Niue','country.nu'),
 (160,'nf','Norfolk Island','country.nf'),
 (161,'kp','North Korea','country.kp'),
 (162,'mp','Northern Mariana Islands','country.mp'),
 (163,'no','Norway','country.no'),
 (164,'om','Oman','country.om'),
 (165,'pk','Pakistan','country.pk'),
 (166,'pw','Palau','country.pw'),
 (167,'ps','Palestinian Territories','country.ps'),
 (168,'pa','Panama','country.pa'),
 (169,'pg','Papua New Guinea','country.pg'),
 (170,'py','Paraguay','country.py'),
 (171,'pe','Peru','country.pe'),
 (172,'ph','Philippines','country.ph'),
 (173,'pn','Pitcairn Islands','country.pn'),
 (174,'pl','Poland','country.pl'),
 (175,'pt','Portugal','country.pt'),
 (176,'pr','Puerto Rico','country.pr'),
 (177,'qa','Qatar','country.qa'),
 (178,'re','Reunion','country.re'),
 (179,'ro','Romania','country.ro'),
 (180,'ru','Russia','country.ru'),
 (181,'rw','Rwanda','country.rw'),
 (182,'sh','Saint Helena and Dependencies','country.sh'),
 (183,'kn','Saint Kitts and Nevis','country.kn'),
 (184,'lc','Saint Lucia','country.lc'),
 (185,'pm','Saint Pierre and Miquelon','country.pm'),
 (186,'vc','Saint Vincent and the Grenadines','country.vc'),
 (187,'ws','Samoa','country.ws'),
 (188,'sm','San Marino','country.sm'),
 (189,'st','Sao Tome and Principe','country.st'),
 (190,'sa','Saudi Arabia','country.sa'),
 (191,'sn','Senegal','country.sn'),
 (192,'sc','Seychelles','country.sc'),
 (193,'sl','Sierra Leone','country.sl'),
 (194,'sg','Singapore','country.sg'),
 (195,'sk','Slovakia','country.sk'),
 (196,'si','Slovenia','country.si'),
 (197,'sb','Solomon Islands','country.sb'),
 (198,'so','Somalia','country.so'),
 (199,'za','South Africa','country.za'),
 (200,'gs','South Georgia and South Sandwich Islands','country.gs'),
 (201,'kr','South Korea','country.kr'),
 (202,'es','Spain','country.es'),
 (203,'pi','Spratly Islands','country.pi'),
 (204,'lk','Sri Lanka','country.lk'),
 (205,'sd','Sudan','country.sd'),
 (206,'sr','Suriname','country.sr'),
 (207,'sj','Svalbard and Jan Mayen','country.sj'),
 (208,'sz','Swaziland','country.sz'),
 (209,'se','Sweden','country.se'),
 (210,'ch','Switzerland','country.ch'),
 (211,'sy','Syria','country.sy'),
 (212,'tw','Taiwan','country.tw'),
 (213,'tj','Tajikistan','country.tj'),
 (214,'tz','Tanzania','country.tz'),
 (215,'th','Thailand','country.th'),
 (216,'tg','Togo','country.tg'),
 (217,'tk','Tokelau','country.tk'),
 (218,'to','Tonga','country.to'),
 (219,'tt','Trinidad and Tobago','country.tt'),
 (220,'tn','Tunisia','country.tn'),
 (221,'tr','Turkey','country.tr'),
 (222,'tm','Turkmenistan','country.tm'),
 (223,'tc','Turks And Caicos Islands','country.tc'),
 (224,'tv','Tuvalu','country.tv'),
 (225,'ug','Uganda','country.ug'),
 (226,'ua','Ukraine','country.ua'),
 (227,'ae','United Arab Emirates','country.ae'),
 (228,'uk','United Kingdom','country.uk'),
 (229,'us','United States','country.us'),
 (230,'um','United States Minor Outlying Islands','country.um'),
 (231,'uy','Uruguay','country.uy'),
 (232,'vi','US Virgin Islands','country.vi'),
 (233,'uz','Uzbekistan','country.uz'),
 (234,'vu','Vanuatu','country.vu'),
 (235,'va','Vatican City','country.va'),
 (236,'ve','Venezuela','country.ve'),
 (237,'vn','Vietnam','country.vn'),
 (238,'wf','Wallis and Futuna','country.wf'),
 (239,'eh','Western Sahara','country.eh'),
 (240,'ye','Yemen','country.ye'),
 (241,'zm','Zambia','country.zm'),
 (242,'zw','Zimbabwe','country.zw'),
 (243,'rs','Serbia','country.rs'),
 (244,'me','Montenegro','country.me');

INSERT INTO `Province` (`ProvinceID`,`Code`,`Name`,`CountryID`,`LanguageKey`,`DisplayOrder`) VALUES 
 (1,'ANGIANG','An Giang',237,'province.angiang',1),
 (2,'VUNGTAU','Bà Rịa - Vũng Tàu',237,'province.vungtau',2),
 (3,'BACLIEU','Bạc Liêu',237,'province.baclieu',3),
 (4,'BACKAN','Bắc Kạn',237,'province.backan',4),
 (5,'BACGIANG','Bắc Giang',237,'province.bacgiang',5),
 (6,'BACNINH','Bắc Ninh',237,'province.bacninh',6),
 (7,'BENTRE','Bến Tre',237,'province.bentre',7),
 (8,'BINHDUONG','Bình Dương',237,'province.binhduong',8),
 (9,'BINHDINH','Bình Định',237,'province.binhdinh',9),
 (10,'BINHPHUOC','Bình Phước',237,'province.binhphuoc',10),
 (11,'BINHTHUAN','Bình Thuận',237,'province.binhthuan',11),
 (12,'CAMAU','Cà Mau',237,'province.camau',12),
 (13,'CAOBANG','Cao Bằng',237,'province.caobang',13),
 (14,'CANTHO','Cần Thơ',237,'province.cantho',14),
 (15,'DANANG','Đà Nẵng',237,'province.danang',15),
 (16,'DAKLAK','Đắk Lắk',237,'province.daklak',16),
 (17,'DAKNONG','Đắk Nông',237,'province.daknong',17),
 (18,'DONGNAI','Đồng Nai',237,'province.dongnai',18),
 (19,'DONGTHAP','Đồng Tháp',237,'province.dongthap',19),
 (20,'DIENBIEN','Điện Biên',237,'province.dienbien',20),
 (21,'GIALAI','Gia Lai',237,'province.gialai',21),
 (22,'HAGIANG','Hà Giang',237,'province.hagiang',22),
 (23,'HANAM','Hà Nam',237,'province.hanam',23),
 (24,'HANOI','TP. Hà Nội',237,'province.hanoi',24),
 (25,'HATAY','Hà Tây',237,'province.hatay',25),
 (26,'HATINH','Hà Tĩnh',237,'province.hatinh',26),
 (27,'HAIDUONG','Hải Dương',237,'province.haiduong',27),
 (28,'HAIPHONG','Hải Phòng',237,'province.haiphong',28),
 (29,'HOABINH','Hòa Bình',237,'province.hoabinh',29),
 (30,'HAUGIANG','Hậu Giang',237,'province.haugiang',30),
 (31,'HUNGYEN','Hưng Yên',237,'province.hungyen',31),
 (32,'HCM','TP. Hồ Chí Minh',237,'province.hcm',32),
 (33,'KHANHHOA','Khánh Hòa',237,'province.khanhhoa',33),
 (34,'KIENGIANG','Kiên Giang',237,'province.kiengiang',34),
 (35,'KONTUM','Kon Tum',237,'province.kontum',35),
 (36,'LAICHAU','Lai Châu',237,'province.laichau',36),
 (37,'LAOCAI','Lào Cai',237,'province.laocai',37),
 (38,'LANGSON','Lạng Sơn',237,'province.langson',38),
 (39,'LAMDONG','Lâm Đồng',237,'province.lamdong',39),
 (40,'LONGAN','Long An',237,'province.longan',40),
 (41,'NAMDINH','Nam Định',237,'province.namdinh',41),
 (42,'NGHEAN','Nghệ An',237,'province.nghean',42),
 (43,'NINHBINH','Ninh Bình',237,'province.ninhbinh',43),
 (44,'NINHTHUAN','Ninh Thuận',237,'province.ninhthuan',44),
 (45,'PHUTHO','Phú Thọ',237,'province.phutho',45),
 (46,'PHUYEN','Phú Yên',237,'province.phuyen',46),
 (47,'QUANGBINH','Quảng Bình',237,'province.quangbinh',47),
 (48,'QUANGNAM','Quảng Nam',237,'province.quangnam',48),
 (49,'QUANGNGAI','Quảng Ngãi',237,'province.quangngai',49),
 (50,'QUANGNING','Quảng Ninh',237,'province.quangning',50),
 (51,'QUANGTRI','Quảng Trị',237,'province.quangtri',51),
 (52,'SOCTRANG','Sóc Trăng',237,'province.soctrang',52),
 (53,'SONLA','Sơn La',237,'province.sonla',53),
 (54,'TAYNINH','Tây Ninh',237,'province.tayninh',54),
 (55,'THAIBINH','Thái Bình',237,'province.thaibinh',55),
 (56,'THAINGUYEN','Thái Nguyên',237,'province.thainguyen',56),
 (57,'THANHHOA','Thanh Hóa',237,'province.thanhhoa',57),
 (58,'HUE','Thừa Thiên - Huế',237,'province.hue',58),
 (59,'TIENGIANG','Tiền Giang',237,'province.tiengiang',59),
 (60,'TRAVINH','Trà Vinh',237,'province.travinh',60),
 (61,'TUYENQUANG','Tuyên Quang',237,'province.tuyenquang',61),
 (62,'VINHLONG','Vĩnh Long',237,'province.vinhlong',62),
 (63,'VINHPHUC','Vĩnh Phúc',237,'province.vinhphuc',63),
 (64,'YENBAI','Yên Bái',237,'province.yenbai',64);

 
 INSERT INTO `City` (`CityID`,`CountryID`,`Code`,`Name`,`LanguageKey`) VALUES 
 (1,237,'ANGIANG_VN','An Giang, Vietnam','city.vn.angiang'),
 (2,237,'VUNGTAU_VN','Bà Rịa - Vũng Tàu, Vietnam','city.vn.vungtau'),
 (3,237,'BACLIEU_VN','Bạc Liêu, Vietnam','city.vn.baclieu'),
 (4,237,'BACKAN_VN','Bắc Kạn, Vietnam','city.vn.backan'),
 (5,237,'BACGIANG_VN','Bắc Giang, Vietnam','city.vn.bacgiang'),
 (6,237,'BACNINH_VN','Bắc Ninh, Vietnam','city.vn.bacninh'),
 (7,237,'BENTRE_VN','Bến Tre, Vietnam','city.vn.bentre'),
 (8,237,'BINHDUONG_VN','Bình Dương, Vietnam','city.vn.binhduong'),
 (9,237,'BINHDINH_VN','Bình Định, Vietnam','city.vn.binhdinh'),
 (10,237,'BINHPHUOC_VN','Bình Phước, Vietnam','city.vn.binhphuoc'),
 (11,237,'BINHTHUAN_VN','Bình Thuận, Vietnam','city.vn.binhthuan'),
 (12,237,'CAMAU_VN','Cà Mau, Vietnam','city.vn.camau'),
 (13,237,'CAOBANG_VN','Cao Bằng, Vietnam','city.vn.caobang'),
 (14,237,'CANTHO_VN','Cần Thơ, Vietnam','city.vn.cantho'),
 (15,237,'DANANG_VN','Đà Nẵng, Vietnam','city.vn.danang'),
 (16,237,'DAKLAK_VN','Đắk Lắk, Vietnam','city.vn.daklak'),
 (17,237,'DAKNONG_VN','Đắk Nông, Vietnam','city.vn.daknong'),
 (18,237,'DONGNAI_VN','Đồng Nai, Vietnam','city.vn.dongnai'),
 (19,237,'DONGTHAP_VN','Đồng Tháp, Vietnam','city.vn.dongthap'),
 (20,237,'DIENBIEN_VN','Điện Biên, Vietnam','city.vn.dienbien'),
 (21,237,'GIALAI_VN','Gia Lai, Vietnam','city.vn.gialai'),
 (22,237,'HAGIANG_VN','Hà Giang, Vietnam','city.vn.hagiang'),
 (23,237,'HANAM_VN','Hà Nam, Vietnam','city.vn.hanam'),
 (24,237,'HANOI_VN','TP. Hà Nội, Vietnam','city.vn.hanoi'),
 (25,237,'HATAY_VN','Hà Tây, Vietnam','city.vn.hatay'),
 (26,237,'HATINH_VN','Hà Tĩnh, Vietnam','city.vn.hatinh'),
 (27,237,'HAIDUONG_VN','Hải Dương, Vietnam','city.vn.haiduong'),
 (28,237,'HAIPHONG_VN','Hải Phòng, Vietnam','city.vn.haiphong'),
 (29,237,'HOABINH_VN','Hòa Bình, Vietnam','city.vn.hoabinh'),
 (30,237,'HAUGIANG_VN','Hậu Giang, Vietnam','city.vn.haugiang'),
 (31,237,'HUNGYEN_VN','Hưng Yên, Vietnam','city.vn.hungyen'),
 (32,237,'HCM_VN','TP. Hồ Chí Minh, Vietnam','city.vn.hcm'),
 (33,237,'KHANHHOA_VN','Khánh Hòa, Vietnam','city.vn.khanhhoa'),
 (34,237,'KIENGIANG_VN','Kiên Giang, Vietnam','city.vn.kiengiang'),
 (35,237,'KONTUM_VN','Kon Tum, Vietnam','city.vn.kontum'),
 (36,237,'LAICHAU_VN','Lai Châu, Vietnam','city.vn.laichau'),
 (37,237,'LAOCAI_VN','Lào Cai, Vietnam','city.vn.laocai'),
 (38,237,'LANGSON_VN','Lạng Sơn, Vietnam','city.vn.langson'),
 (39,237,'LAMDONG_VN','Lâm Đồng, Vietnam','city.vn.lamdong'),
 (40,237,'LONGAN_VN','Long An, Vietnam','city.vn.longan'),
 (41,237,'NAMDINH_VN','Nam Định, Vietnam','city.vn.namdinh'),
 (42,237,'NGHEAN_VN','Nghệ An, Vietnam','city.vn.nghean'),
 (43,237,'NINHBINH_VN','Ninh Bình, Vietnam','city.vn.ninhbinh'),
 (44,237,'NINHTHUAN_VN','Ninh Thuận, Vietnam','city.vn.ninhthuan'),
 (45,237,'PHUTHO_VN','Phú Thọ, Vietnam','city.vn.phutho'),
 (46,237,'PHUYEN_VN','Phú Yên, Vietnam','city.vn.phuyen'),
 (47,237,'QUANGBINH_VN','Quảng Bình, Vietnam','city.vn.quangbinh'),
 (48,237,'QUANGNAM_VN','Quảng Nam, Vietnam','city.vn.quangnam'),
 (49,237,'QUANGNGAI_VN','Quảng Ngãi, Vietnam','city.vn.quangngai'),
 (50,237,'QUANGNING_VN','Quảng Ninh, Vietnam','city.vn.quangning'),
 (51,237,'QUANGTRI_VN','Quảng Trị, Vietnam','city.vn.quangtri'),
 (52,237,'SOCTRANG_VN','Sóc Trăng, Vietnam','city.vn.soctrang'),
 (53,237,'SONLA_VN','Sơn La, Vietnam','city.vn.sonla'),
 (54,237,'TAYNINH_VN','Tây Ninh, Vietnam','city.vn.tayninh'),
 (55,237,'THAIBINH_VN','Thái Bình, Vietnam','city.vn.thaibinh'),
 (56,237,'THAINGUYEN_VN','Thái Nguyên, Vietnam','city.vn.thainguyen'),
 (57,237,'THANHHOA_VN','Thanh Hóa, Vietnam','city.vn.thanhhoa'),
 (58,237,'HUE_VN','Thừa Thiên - Huế, Vietnam','city.vn.hue'),
 (59,237,'TIENGIANG_VN','Tiền Giang, Vietnam','city.vn.tiengiang'),
 (60,237,'TRAVINH_VN','Trà Vinh, Vietnam','city.vn.travinh'),
 (61,237,'TUYENQUANG_VN','Tuyên Quang, Vietnam','city.vn.tuyenquang'),
 (62,237,'VINHLONG_VN','Vĩnh Long, Vietnam','city.vn.vinhlong'),
 (63,237,'VINHPHUC_VN','Vĩnh Phúc, Vietnam','city.vn.vinhphuc'),
 (64,237,'YENBAI_VN','Yên Bái, Vietnam','city.vn.yenbai');
 
 INSERT INTO `UserAdmin` (`UserAdminID`,`UserName`,`Password`,`FullName`,`Email`,`Status`,`Role`,`CreatedDate`,`ModifiedDate`) VALUES 
 (1,'admin','ret4vDdtRpk=','Le Trung Hieu','hieu.le@hoanghacgroup.com',1,'ADMIN','2016-10-08 22:27:10',NULL);